FROM openjdk:11-jre-slim

# Add a volume pointing to /tmp, spring writes to it
VOLUME /tmp

# The application's jar file
ARG JAR_FILE=target/cm-0.0.1-SNAPSHOT.jar

# Add the application's jar to the container
ADD ${JAR_FILE} cm.jar

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/cm.jar"]
